// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: DeleteById.sql

package db

import (
	"context"
)

const deleteById = `-- name: DeleteById :exec
delete from users where id = $1
`

func (q *Queries) DeleteById(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteById, id)
	return err
}
