// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: Delete.sql

package db

import (
	"context"
)

const delete = `-- name: Delete :exec
delete from users where id = $1
`

func (q *Queries) Delete(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}
