// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: GetOne.sql

package db

import (
	"context"
)

const getOne = `-- name: GetOne :one
select id,
       email,
       first_name,
       last_name,
       password,
       user_active,
       created_at,
       updated_at
from users
where id = $1
`

func (q *Queries) GetOne(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getOne, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Password,
		&i.UserActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
