// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: ResetPassword.sql

package db

import (
	"context"
)

const resetPassword = `-- name: ResetPassword :exec
update users set password = $1 where id = $2
`

type ResetPasswordParams struct {
	Password string `json:"password"`
	ID       int32  `json:"id"`
}

func (q *Queries) ResetPassword(ctx context.Context, arg ResetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, resetPassword, arg.Password, arg.ID)
	return err
}
