// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: Update.sql

package db

import (
	"context"
	"time"
)

const update = `-- name: Update :exec
update users set
                 email = $1,
                 first_name = $2,
                 last_name = $3,
                 user_active = $4,
                 updated_at = $5
where id = $6
`

type UpdateParams struct {
	Email      string    `json:"email"`
	FirstName  string    `json:"first_name"`
	LastName   string    `json:"last_name"`
	UserActive int32     `json:"user_active"`
	UpdatedAt  time.Time `json:"updated_at"`
	ID         int32     `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) error {
	_, err := q.db.ExecContext(ctx, update,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.UserActive,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
